/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package money_counter;

import java.awt.Cursor;
import java.awt.List;
import java.text.DecimalFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;

/**
 *
 * @author Matúš
 */
public class Count_Euro_Form extends javax.swing.JFrame 
{

    /**
     *
     */
    public ArrayList<JSpinner> mylist = new ArrayList<JSpinner>();

    public ArrayList<Integer> list_int_numbers = new ArrayList<Integer>();
    
    
    /**
     * Creates new form Count_Euro_Form
     */
    public Count_Euro_Form() {
        initComponents(); 
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
        
        Fill_List();
        
        list_int_numbers.add(500);
        list_int_numbers.add(200);
        list_int_numbers.add(100);
        list_int_numbers.add(50);
        list_int_numbers.add(20);
        list_int_numbers.add(10);
        list_int_numbers.add(5);
        list_int_numbers.add(2);
        list_int_numbers.add(1);
        
        Background_Class b = new Background_Class();
        b.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner_50_e = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner_0_50_e = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner_200_e = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSpinner_100_e = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinner_20_e = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_500_e = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_0_10_e = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinner_5_e = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSpinner_0_1_e = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_1_e = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinner_10_e = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner_0_20_e = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinner_2_e = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jSpinner_0_5_e = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jSpinner_0_2_e = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        result_number_label = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        reset_lable = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1230, 661));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSpinner_50_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 213, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/200_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,01 cent.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, -1, -1));
        getContentPane().add(jSpinner_0_50_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 213, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/20_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));
        getContentPane().add(jSpinner_200_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 213, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/100_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        getContentPane().add(jSpinner_100_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 213, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/50_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));
        getContentPane().add(jSpinner_20_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 213, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/500_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 91, -1, -1));
        getContentPane().add(jSpinner_500_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 105, 213, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/10_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));
        getContentPane().add(jSpinner_0_10_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 213, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/5_Euro.Recto.printcode_place.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));
        getContentPane().add(jSpinner_5_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 213, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/2 euro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));
        getContentPane().add(jSpinner_0_1_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 460, 213, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/1 euro.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));
        getContentPane().add(jSpinner_1_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 213, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,50 cent.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));
        getContentPane().add(jSpinner_10_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 213, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,20 cent.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,20 cent.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));
        getContentPane().add(jSpinner_0_20_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 213, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,10 cent.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, -1, -1));
        getContentPane().add(jSpinner_2_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 213, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,05 cent.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, -1, -1));
        getContentPane().add(jSpinner_0_5_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 213, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/0,02 cent.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, -1, -1));
        getContentPane().add(jSpinner_0_2_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, 213, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Total amount:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, -1, -1));

        result_number_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        result_number_label.setText("jLabel17");
        result_number_label.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                result_number_labelAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(result_number_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        reset_lable.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matúš\\Desktop\\button_reset.png")); // NOI18N
        reset_lable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                reset_lableMouseMoved(evt);
            }
        });
        reset_lable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_lableMouseClicked(evt);
            }
        });
        getContentPane().add(reset_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/background.png"))); // NOI18N
        jLabel17.setText("jLabel2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void result_number_labelAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_result_number_labelAncestorMoved
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_result_number_labelAncestorMoved

    private void reset_lableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_lableMouseClicked
            
        Set_JSpinners_On_Default_Value();
    }//GEN-LAST:event_reset_lableMouseClicked

    private void reset_lableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_lableMouseMoved
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        reset_lable.setCursor(c);   
    }//GEN-LAST:event_reset_lableMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Count_Euro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Count_Euro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Count_Euro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Count_Euro_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Count_Euro_Form c = new Count_Euro_Form();
                c.setVisible(true);
                
                
                
              
               
            }
        });
    }
    
    public void Fill_List()
    {
        mylist.add(jSpinner_500_e);
        mylist.add(jSpinner_200_e); 
        mylist.add(jSpinner_100_e);
        mylist.add(jSpinner_50_e);
        mylist.add(jSpinner_20_e);
        mylist.add(jSpinner_10_e);
        mylist.add(jSpinner_5_e);
        mylist.add(jSpinner_2_e);
        mylist.add(jSpinner_1_e);
        mylist.add(jSpinner_0_50_e);
        mylist.add(jSpinner_0_20_e);
        mylist.add(jSpinner_0_10_e);
        mylist.add(jSpinner_0_5_e); 
        mylist.add(jSpinner_0_2_e);
        mylist.add(jSpinner_0_1_e);
        
    }
    
    public class Background_Class extends Thread
    {
        int result;
        @Override
        public void run()
        {
             while(true) 
             {   
                result = (int)jSpinner_500_e.getValue()*500+(int)jSpinner_200_e.getValue()*200+(int)jSpinner_100_e.getValue()*100+
                (int)jSpinner_50_e.getValue()*50+(int)jSpinner_20_e.getValue()*20+(int)jSpinner_10_e.getValue()*10+(int)jSpinner_5_e.getValue()*5+
                (int)jSpinner_2_e.getValue()*2+(int)jSpinner_1_e.getValue()*1;
                
                float result_float_numbers = (int)jSpinner_0_50_e.getValue()*(float)0.50f + (int)jSpinner_0_20_e.getValue()*(float)0.20f + (int)jSpinner_0_10_e.getValue()*(float)0.10f +
                (int)jSpinner_0_5_e.getValue()*(float)0.05f + (int)jSpinner_0_2_e.getValue()*(float)0.02f + (int)jSpinner_0_1_e.getValue()*(float)0.01f;
               
                
                float res = result + result_float_numbers;
                DecimalFormat df = new DecimalFormat("0.00");
                result_number_label.setText(df.format(res)+" €");
                            
                /* 
                for(int i = 0; i < mylist.size()-6; i++) 
                {
                   result += (int)mylist.get(i).getValue()*list_int_numbers.get(i);
                }
                */  
                
                
                // next way for more efficiant code is to create helpful method for checking, if some of the mylist items would not be null, in that case
                // this cycle will be performed
             }
        }
    }       // class in the background for updating my result
    
   
    
    public void Set_JSpinners_On_Default_Value()
    {
       for(int i = 0; i < mylist.size(); i++) 
       {
            mylist.get(i).setValue(0);
       } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner_0_10_e;
    private javax.swing.JSpinner jSpinner_0_1_e;
    private javax.swing.JSpinner jSpinner_0_20_e;
    private javax.swing.JSpinner jSpinner_0_2_e;
    private javax.swing.JSpinner jSpinner_0_50_e;
    private javax.swing.JSpinner jSpinner_0_5_e;
    private javax.swing.JSpinner jSpinner_100_e;
    private javax.swing.JSpinner jSpinner_10_e;
    private javax.swing.JSpinner jSpinner_1_e;
    private javax.swing.JSpinner jSpinner_200_e;
    private javax.swing.JSpinner jSpinner_20_e;
    private javax.swing.JSpinner jSpinner_2_e;
    private javax.swing.JSpinner jSpinner_500_e;
    private javax.swing.JSpinner jSpinner_50_e;
    private javax.swing.JSpinner jSpinner_5_e;
    private javax.swing.JLabel reset_lable;
    private javax.swing.JLabel result_number_label;
    // End of variables declaration//GEN-END:variables
}
