/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package money_counter;

import java.awt.Cursor;
import java.awt.Toolkit;

/**
 *
 * @author Matúš
 */
public class Start_Form extends javax.swing.JFrame {

    /**
     * Creates new form Start_Form
     */
    public Start_Form() {
        initComponents();
        this.setLocationRelativeTo(null);        // Form will be showed in center of screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        euro_button = new javax.swing.JLabel();
        dolar_button = new javax.swing.JLabel();
        british_pound_button = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1230, 661));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/money counter title.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 28, -1, -1));

        euro_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/euro.png"))); // NOI18N
        euro_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                euro_buttonMouseMoved(evt);
            }
        });
        euro_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                euro_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(euro_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 295, -1, -1));

        dolar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/dolar.png"))); // NOI18N
        dolar_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dolar_buttonMouseMoved(evt);
            }
        });
        getContentPane().add(dolar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 295, -1, -1));

        british_pound_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/british pound.png"))); // NOI18N
        british_pound_button.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                british_pound_buttonMouseMoved(evt);
            }
        });
        getContentPane().add(british_pound_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 297, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/background.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dolar_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolar_buttonMouseMoved
        // TODO add your handling code here:
        
         Cursor c = new Cursor(Cursor.HAND_CURSOR);
        dolar_button.setCursor(c); 
    }//GEN-LAST:event_dolar_buttonMouseMoved

    private void euro_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euro_buttonMouseMoved
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        euro_button.setCursor(c);   
    }//GEN-LAST:event_euro_buttonMouseMoved

    private void british_pound_buttonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_british_pound_buttonMouseMoved
        
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        british_pound_button.setCursor(c); 
    }//GEN-LAST:event_british_pound_buttonMouseMoved

    private void euro_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_euro_buttonMouseClicked
        
        setVisible(false);                          // Start Form will disapear
        Count_Euro_Form f = new Count_Euro_Form();      // Register Form will be showed
       
        f.setVisible(true); 
    }//GEN-LAST:event_euro_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel british_pound_button;
    private javax.swing.JLabel dolar_button;
    private javax.swing.JLabel euro_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
